### ISSUE TITLE
Larger font sizes for high-dpi screens

### ISSUE THREAD

**Issue by davidscholberg** [hchargois/gohufont#4]
I am a huge fan of Gohufont. It solves all of the little annoying things about Terminus, such as the "ell" and "one" similarities and clearer-looking lowercase "g" and "y", etc.

However, I have a laptop with a fairly high-dpi screen (~175 DPI), and the 14 size font is too small for that screen. I have to use Terminus 20 in order for the font to be readable.

Is there any chance you'll work on larger font sizes for Gohufont?

**Comment by hchargois** [comment]
Thank you for expressing your appreciation :)
However, I am sorry to say that I don't plan on working on any other size of the font.
I know that it is customary for "normal DPI" images and fonts to be scaled by a factor of 2 on "high DPI" screens. Maybe you could try that? You could double the 11-pt size to have an effective 22-pt in all its bitmappy glory. How to actually do that, of course, is left as an exercise to the reader.

**Comment by hchargois** [comment]
There are now "double-size" versions available :)
https://github.com/hchargois/gohufont/tree/master/hidpi
