### ISSUE TITLE
Raise < and > by 1px on the 14px version

### ISSUE THREAD

**Issue by tobia** [hchargois/gohufont#5]
I've been using GohuFont (14px) for a long time and I've always noticed an oddity: the ASCII arrows `<-` `->` `<=` `=>` used by some languages (PHP, Haskell, etc.) do not line up correctly:

![gohu](https://cloud.githubusercontent.com/assets/48756/15476060/6acec6e4-210d-11e6-969e-779900446e58.png)

I suppose that the original intention was to make the lowercase HTML tags prettier, but this makes the `<` and `>` symbols look wrong both for ASCII arrows and for their original numeric purpose:

![gohu2](https://cloud.githubusercontent.com/assets/48756/15476476/7bfea8b0-210f-11e6-9ada-44583c0f5c0e.png)

I checked several monospaced fonts and they all center these symbols with respect to the uppercase letters and numbers, not to the lowercase ones. 

Would you accept a pull request to raise them by 1px?

**Comment by hchargois** [comment]
You are right. I've fixed it. Thank you!
